name: book_summary
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.3
  google_generative_ai: ^0.4.3
  pdf_image_renderer: ^0.7.0
  file_picker: ^8.0.6
  loading_animation_widget: ^1.2.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  http: ^1.2.1
  flutter_staggered_grid_view: ^0.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  rate: ^0.0.2
  intl: ^0.19.0
  cloud_firestore: ^4.17.5
  toastification: ^2.1.0
  just_audio: ^0.9.39
  dio: ^5.5.0+1
  firebase_storage: ^11.7.7
  day_night_themed_switch: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 20

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/